version: 2.1

orbs:
  node: circleci/node@4.7.0

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:14.17.5

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths: .
  bump-version: 
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Setup Email
          command: git config user.email "username@mydomain.com"
      - run:
          name: Setup Name
          command: git config user.name "My Name"
      - run:
          name: Bump Version
          command: npm version patch -m "Upgrading to %s"
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Push Change
          command: git push origin $CIRCLE_BRANCH
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish to NPM
          command: yarn publish --access public --non-interactive
workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore: main
      - bump-version:
          requires:
            - test
          filters:
            branches:
              ignore: main
  production:
    jobs:
      - test:
          filters:
            &filters-production # this yaml anchor is setting these values to "filters-production"
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - publish:
          context: NPM_Publish
          requires:
            - test
          filters:
            <<: *filters-production # this is calling the previously set yaml anchor
