version: 2.1

orbs:
  node: circleci/node@4.7.0

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:18.15.0

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - run: yarn test
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Execute Semantic Release
          command: yarn semantic-release
workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore: main
  production:
    jobs:
      - test:
          filters:
            &filters-production # this yaml anchor is setting these values to "filters-production"
            branches:
              only: main
      - publish:
          context: NPM_Publish
          requires:
            - test
          filters:
            <<: *filters-production # this is calling the previously set yaml anchor
