/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AirWild2Sale } from "./AirWild2Sale";
export type { WolfSale } from "./WolfSale";

export { AirWild2Sale__factory } from "./factories/AirWild2Sale__factory";
export { WolfSale__factory } from "./factories/WolfSale__factory";
